services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wellness
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres -d wellness"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  wellness-resource-service:
    build:
      context: ./wellness-resource-service
    image: wellness-resource-service:1.0.0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8081:8081"

  # --- Event DB ---


  event-db:
    image: postgres:16-alpine
    container_name: event-db
    environment:
      POSTGRES_DB: eventdb
      POSTGRES_USER: event_user
      POSTGRES_PASSWORD: event_pass
    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U event_user -d eventdb" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - eventdb_data:/var/lib/postgresql/data

  # --- Event Service ---

  event-service:
    build:
      context: ./event-service
    container_name: event-service
    depends_on:
      event-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://event-db:5432/eventdb
      SPRING_DATASOURCE_USERNAME: event_user
      SPRING_DATASOURCE_PASSWORD: event_pass
      SERVER_PORT: 8083
    ports:
      - "8083:8083"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8083/actuator/health"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  eventdb_data: